### ISSUE TITLE
Summarize this thread on typing vs. copy-and-paste

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/teachtogether.tech#188]
https://carpentries.topicbox.com/groups/discuss/Taf27bc5ac21f2829

**Comment by tedyoung** [comment]
Where were you thinking the most appropriate place for this is?

The gist seems to be: better learning (through retrieval practice) for typing vs. keeping up with the pace of the class. A "when to type" vs. "when to copy-n-paste" table might be appropriate?

**Comment by erictleung** [comment]
After reading through the thread, it looks like this might be best in the "Expertise and Memory" lesson, in my opinion.

In my understanding of the thread, having to type out commands increases retention of commands, critical thinking of how to use those commands, and fluency in using commands, in addition to points brought up by @tedyoung.

I also considered the "Cognitive Load" lesson because copy-paste vs typing does change your cognitive load on running commands, but I think it is more of an expertise and memory sort of topic.

So this could go well after the "Becoming an Expert" section. Thoughts?

**Comment by erictleung** [comment]
A unique perspective on copy-pasting vs typing in the context of live-coding:

> "Copy-pasting is not cheating, it's the correct way to prevent bugs."

Source: https://twitter.com/tapundemek/status/1090330296313102336
