### ISSUE TITLE
epub problems (fixed)

### ISSUE THREAD

**Issue by eshellman** [gvwilson/teachtogether.tech#193]
bad html caused the epub to fail in some readers. I have fixed the epub and mobi and made them available at https://unglue.it/work/313918/

Use your fave html tidy equivalent to clean the html; there are many unclosed `<code>` tags that epub readers handle poorly.

I've also added a TOC and the cover.

Suggestions:
 - put the ebook files in your release folder rather than the git tree - and tag the repo with a version number.
 - look at HTMLBook for guidelines to make the html directly zippable into epub; pandoc does all sorts of gymnastics to just zip the files. https://github.com/oreillymedia/HTMLBook
 - I don't think you need any pandoc or TeX at all!
 - consider using a book.json file to define the structure of the ebook the way GitBook does, or use index.html to define a the level table of contents. If you do that, Calibre should be able to make the epub for you.

**Comment by gvwilson** [comment]
Thanks very much @eshellman - the EPUB and MOBI versions are generated with Pandoc, and I assumed that it would get it right.  I'd like to incorporate your fixes into the build process so that future updates don't require any manual labor - I'll see if I can find a volunteer to grind through it.

Thanks very much once again,
Greg
